version: "3.3"

services:
  app:
    container_name: avantposte
    image: avantposte
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/static:/app/static
